env:
  browser: true
  es2021: true
  amd: true
  es6: true
  jquery: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: detect

