version: '3.7'
volumes:
  postgres_data: {}
  esdata: {}
services:
  dow_app:
    tty: true
    stdin_open: true
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres@db:5432/DevOfWeeks_development
      - PORT=3000
    build:
      context: .
      dockerfile: ./docker/DockerFile
    depends_on:
      - redis
      - db
    volumes:
      - .:/var/www/app
    ports:
      - 3001:3000
  db:
    image: postgres:11.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 8004:5432
  redis:
    image: redis